version: 1
accounts:
  - name: alice
    coins: ["20000token", "200000000stake"]
  - name: bob
    coins: ["10000token", "100000000stake"]
validators:
  - name: alice
    bonded: "100000000stake"
faucet:
  name: bob
  coins: ["5token", "100000stake"]

init:
  client:
    chain-id: "greenfield_9000-1"

genesis:
  chain_id: "greenfield_9000-1"
